### ISSUE TITLE
react 18.0 compatibility

### ISSUE THREAD

**Issue by holem** [alirezatav/react-timeline#2]
Hi there! 

First of all - thanks for the great job you have done!

But unfortunately, it seams that the project is not compatible with react v18.0 
React crashes with this:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:1)
    at useRef (react.development.js:1515:1)
    at Timeline (index.js:67:1)
    at renderWithHooks (react-dom.development.js:16141:1)
    at mountIndeterminateComponent (react-dom.development.js:20838:1)
    at beginWork (react-dom.development.js:22342:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4157:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:1)
    at invokeGuardedCallback (react-dom.development.js:4270:1)
    at beginWork$1 (react-dom.development.js:27243:1)
```

Do you have some ideas on how to fix that? 
Thanks!

**Comment by alirezatav** [comment]
Thank you very much for your remark @holem
